### ISSUE TITLE
Scrutinizer should use the COMPOSER_ROOT_VERSION for PhpAnalyzer

### ISSUE THREAD

**Issue by stof** [scrutinizer-ci/scrutinizer#120]
Composer tries to guess the version of the root package based on the git or mercurial data (I don't think the support of SVN-based guessing has been merged) and defaults to marking it as 1.0 when it cannot guess it.
The common case where guessing is impossible is when your code is in a detached HEAD (which is the case on scrutinizer, or maybe even without the git repo).

For most packages, this is not an issue as the root package version is never involved in the solving algorithm. However, it breaks the resolution when the root package is itself required by one of its dependency. See https://scrutinizer-ci.com/g/phpspec/phpspec/inspections/1f65aa01-9a49-4e45-8d04-53666993f05f for instance. As you can see, it seems that the guessing even worked on Travis.

The way to solve such cases is to set the `COMPOSER_ROOT_VERSION` before calling Composer. I think you should set it as Scrutinizer should be able to know what to use here. It should be the version for the branch for which the build was triggered (for PRs, use the target branch of the PR, not the feature branch used as source)

**Comment by olvlvl** [comment]
@schmittjoh How does one use the `COMPOSER_ROOT_VERSION` directive with Scrutinizer? I searched the documentation but couldn't find anything about that. I tried to define it [like this other project](https://github.com/php-ddd/specification/blob/master/.scrutinizer.yml) but to no avail. This is my config: https://github.com/ICanBoogie/bind-http/blob/2.6/.scrutinizer.yml

Please, tell me what I should do.
