### ISSUE TITLE
GitHub: link to TravisCI gets hijacked

### ISSUE THREAD

**Issue by JeroenDeDauw** [scrutinizer-ci/scrutinizer#170]
When using Scrutinizer, the build status icon (the one that states one of: passed, failed, error) links to ScrutinizerCI rather than to TravisCI. It's nice to have a link to ScrutinizerCI, though for my team the choice goes to TravisCI if we need to pick one. That is where we want to go when a build fails after all.

**Comment by tonglil** [comment]
I am fairly certain this issue is now resolved by Github.

**Comment by JeroenDeDauw** [comment]
Yeah, it indeed has been resolved
