### ISSUE TITLE
HipChat integration

### ISSUE THREAD

**Issue by rcousens** [scrutinizer-ci/scrutinizer#288]
Would love to be able to integrate automatic inspection results to HipChat!

**Comment by thenetexperts** [comment]
I tried that today, and after the hook is saved, we receive a "tok tok" in hipchat, so it is working.

When a new inspection is finished, we receive the information aswell, however, the analysis part is not showing. It only shows the Analysis headline and not more.

```
The inspection of thenetexperts/repository#master completed.
- Version: BLAH-123 #comment my commit message (94c039)
- Triggered by: thenetexperts

Analysis:
```

Any idea why that is?

**Comment by schmittjoh** [comment]
Do you have a link to the inspection?

**Comment by thenetexperts** [comment]
I have sent you a pm on scrutinizer as the inspections are not public.

**Comment by thenetexperts** [comment]
I THINK that the problem is that in the specific inspection, no changes to the normal issues happened. However, in that specific inspection the code coverage percentage changed. I guess this metric is not being send to hipchat (yet) ?

**Comment by thenetexperts** [comment]
Since this morning it is not working anymore at all. I resetup the token and received a different working setup message, but no inspection results or any kind of notification at all.

I guess you guys are working on it, which is fine by me.

**Comment by schmittjoh** [comment]
There were no changes afaik. Were there inspections that contained changes? It might be easier to open a ticket on the website, so we have a bit more context, then we can help you more easily :)

**Comment by thenetexperts** [comment]
allright, ill do that right away! Thanks!
