### ISSUE TITLE
PHP Analyzer: Determining Dependencies does not recognize caret

### ISSUE THREAD

**Issue by egeloen** [scrutinizer-ci/scrutinizer#290]
Hey!

I just start using caret constraint in composer for one of my project. It seems Scrutinizer is not able to parse caret constraint according to https://scrutinizer-ci.com/g/egeloen/ivory-http-adapter/inspections/5438bf1e-cd62-4d18-85ad-3b2b51aac172 whereas the build is green: https://travis-ci.org/egeloen/ivory-http-adapter/builds/44506481

Can you please update the current composer version used?

**Comment by sagikazarmark** [comment]
+1

**Comment by tonypiper** [comment]
:+1: for fixing.

**Comment by richardmiller** [comment]
:+1: for fixing.

**Comment by schmittjoh** [comment]
This should already be live. 

If you still see this, could you provide a link/open a support ticket? This makes it easier to track this down.

**Comment by richardmiller** [comment]
@schmittjoh  It failed for me when retrying just after your comment - have just tried again and it is now working.

**Comment by richardmiller** [comment]
Oh, jumped the gun. It has failed. I'll put it in a support ticket

**Comment by schmittjoh** [comment]
I think you were probably referring to the test environment (which did indeed still use the old version). This is now updated to the latest version, too.

I'll close this here, feel free to comment/open a ticket if you still run into this.
