### ISSUE TITLE
PHP_CodeSniffer error parametrization

### ISSUE THREAD

**Issue by aik099** [scrutinizer-ci/scrutinizer#293]
Allow parametrization of following PHP_CodeSniffer error for easier removal from inspection results:
```
@category tag comment indented incorrectly; expected 1 spaces but found 11
```
The `@category`, `1` and `11` are parameters.

see https://scrutinizer-ci.com/g/aik099/CodingStandard/inspections/89ee1c5f-6b7f-440a-a503-6a11a3cf0c78/issues/files/CodingStandard/Sniffs/ControlStructures/MultiLineConditionSniff.php?status=new&orderField=path&order=asc#inspectioncomment-432080792

**Comment by schmittjoh** [comment]
I've added a parametrization for this issue; this will only be available
for new issues though, so you'll need to re-run the inspection to take
advantage of it.

**Comment by aik099** [comment]
Great thanks.

Any chance you can also look at #201 ?

**Comment by schmittjoh** [comment]
I'm aware of it, but I cannot promise atm.
