### ISSUE TITLE
Executing commands before analysis

### ISSUE THREAD

**Issue by Anahkiasen** [scrutinizer-ci/scrutinizer#296]
I'm running Scrutinizer on a Laravel application, in order for it to fully understand the code I need to run [this tool](https://github.com/barryvdh/laravel-ide-helper) before analysis which adds docblocks for the proper fields and relations that are usually accessed through magic methods.

I've tried putting it in various hooks, `tests.before`, `project_setup.before`, `dependencies.after` etc but in all cases, the analysis seems to not be affected and starts ahead anyway as soon as the inspection starts.

Is there any way to execute commands before analysis, that would affect the codebase?

**Comment by aik099** [comment]
I've also noticed that PHP_CodeSniffer and PHP Analyzer analysis can start in parallel on different machines.

If you put your commands in `before_commands` key in Scrutinizer CI (e.g. https://scrutinizer-ci.com/g/qa-tools/qa-tools/inspections/699f8329-e6a1-4455-9c85-5021b5f73b2c/config) do they run before anything?

**Comment by schmittjoh** [comment]
@Anahkiasen, unfortunately, that won't be possible. While you could modify the code for some tools (the open-source tools like Code Sniffer), anything that is closed source like PHP Analyzer, or duplicate code detection, would not be affected, and the UI would also not know about these changes. 

btw, not sure you know, but we also have a support ticket system on the website (you should see a "?" in the bottom right) - this is often faster as we have more people looking there :)

@aik099, yes, this is indeed the case, each of the analysis tasks is run in a separate environment often on a different server; the same applies to tests.
