### ISSUE TITLE
Systems outage

### ISSUE THREAD

**Issue by tonglil** [scrutinizer-ci/scrutinizer#300]
Not sure if anyone has reported this, but Scrutinizer seems to be down for the past 2 hours (that was when the last PR stopped getting checked).

Also can see the status for web is down and workers operational, but if that is true then should builds still be occuring?

![screen shot 2015-01-31 at 10 59 01 pm](https://cloud.githubusercontent.com/assets/3250776/5991340/c6b47678-a99c-11e4-9a36-7f8bb7a6bdab.png)

Any updates? Thanks.

**Comment by schmittjoh** [comment]
This has been resolved now.
