### ISSUE TITLE
Incorrect brace position warning

### ISSUE THREAD

**Issue by Anahkiasen** [scrutinizer-ci/scrutinizer#302]
I have the following code:

```php
	/**
	 * @param Topic            $form
	 * @param TopicsRepository $topics
	 */
	public function __construct(
		Topic $form,
		TopicsRepository $topics
	) {
		$this->form   = $form;
		$this->topics = $topics;
	}
```

Despite this being valid [PSR2 formatting](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md#44-method-arguments) I'm getting a warning that the opening brace should be on a new line (instead of `) {`). Is this a bug or a check that I enabled that is causing a conflict with PSR2 or something?

**Comment by schmittjoh** [comment]
Could you link to the issue?

**Comment by Anahkiasen** [comment]
Sorry, time to unignore the issue and reschedule an inspection, here you go https://scrutinizer-ci.com/g/madewithlove/remindme/issues/develop/files/app/Remindme/Commands/TopicsCommandHandler.php?orderField=path&order=asc#inspectioncomment-537576341

**Comment by schmittjoh** [comment]
This warning looks correct. PSR2 wants to have the brace on a new line, i.e. 

```
public function __construct(
    Topic $form,
    TopicsRepository $topics
)
{
}
```

Looks a bit odd in this specific case, you might want to ignore this issue.

**Comment by Anahkiasen** [comment]
I know it wants to have a brace on a new line _in general_ but if you look at the docs I linked in the first post you see this exact usecase being documented and allowed *if* arguments are each on their own line

**Comment by Anahkiasen** [comment]
Exact rule from PSR2 is:

> When the argument list is split across multiple lines, the closing parenthesis and opening brace MUST be placed together on their own line with one space between them.

**Comment by schmittjoh** [comment]
Ah, sorry I totally missed that. Yeah, this is something we will fix, I've created an internal ticket for that.

**Comment by schmittjoh** [comment]
This is fixed in dev, should be coming to production soon.
