### ISSUE TITLE
Github status when inspection is queued

### ISSUE THREAD

**Issue by tonglil** [scrutinizer-ci/scrutinizer#303]
Right now if multiple PRs come up and the account only has 1 container for building, it seems like the queued PRs' status don't change until they actually start building.

Is there a way that once the message is received, the status gets updated? Otherwise sometimes developers still see the green button and don't know if their PR will get built or not.

**Comment by schmittjoh** [comment]
We did indeed not do this. This will be included in the next deployment. I'll already close this issue here, the change is not yet live though.
