### ISSUE TITLE
Failed builds show up as green on Github

### ISSUE THREAD

**Issue by tonglil** [scrutinizer-ci/scrutinizer#304]
Github status shows green, even when it says "errored" and the build failed (specifically due to timeout).

![screen shot 2015-02-10 at 4 16 00 pm](https://cloud.githubusercontent.com/assets/3250776/6139421/55828322-b140-11e4-8728-356bb9a0afb1.png)

**Comment by aik099** [comment]
This is a related issue: #297 where an exception thrown during build run also results in Green build on GitHub with Errored word.

**Comment by schmittjoh** [comment]
This has also been addressed - not yet live though, but will be in the next deployment.
