### ISSUE TITLE
Unrecognized options "include_standards" under "config"  

### ISSUE THREAD

**Issue by Anahkiasen** [scrutinizer-ci/scrutinizer#305]
I'm getting the following Exception when Scrutinizer runs the analyzers (see per example [this build](https://scrutinizer-ci.com/g/madewithlove/remindme/inspections/afa84b5c-a629-49a7-a886-470ea0b260e1)) but I don't seem to be using said option in the [build config](https://scrutinizer-ci.com/profile/build-configs/afe5da28-94f0-4f01-8894-b21b55a82a18) used. Anything changed in the configs that I need to update?

**Comment by schmittjoh** [comment]
This was a problem in our deployment process which has not updated one component. Could you try again, and let me know if this is fixed now?

**Comment by Anahkiasen** [comment]
All good now indeed, thanks
