### ISSUE TITLE
Weeks are duplicated and after coverage glitch one week is missing from stats

### ISSUE THREAD

**Issue by AGmakonts** [scrutinizer-ci/scrutinizer#307]
In stats view there are duplicated weeks for both stats and in addition to that, after having trouble with getting the coverage stats for few days one weeks is missing from the statistic.

![screen shot 2015-02-21 at 16 06 11](https://cloud.githubusercontent.com/assets/4051481/6314567/d493014a-b9e3-11e4-8595-e88b0be17a5c.png)

**Comment by schmittjoh** [comment]
Thanks for opening this; on which repository do you see this behavior?

**Comment by schmittjoh** [comment]
I've moved this to an internal issue. Closing this one here.
