### ISSUE TITLE
Determine composer dependencys fails without identifyable reason

### ISSUE THREAD

**Issue by aimeos** [scrutinizer-ci/scrutinizer#314]
Since using a PHP library for coverals.io, every step for determine dependencys fail, e.g. https://scrutinizer-ci.com/g/aimeos/aimeos-symfony2/inspections/b6ae816e-de60-46f1-ac5a-acc586d75ca9

The only reported error is:
You are using the deprecated option "dev". Dev packages are installed by default now.
LInstalling dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - satooshi/php-coveralls dev-master requires psr/log 1.0.0 -> satisfiable by psr/log[1.0.0].
    - satooshi/php-coveralls dev-master requires psr/log 1.0.0 -> satisfiable by psr/log[1.0.0].
    - Conclusion: don't install psr/log 1.0.0
    - Installation request for satooshi/php-coveralls dev-master -> satisfiable by satooshi/php-coveralls[dev-master].

Locally, everything works fine.

**Comment by schmittjoh** [comment]
I'm not sure what the conflict is here specifically.

As a quick solution, I would suggest to commit your composer.lock file, this also a best practice in general.

**Comment by aimeos** [comment]
OK, that work. Thanks
