### ISSUE TITLE
Config change

### ISSUE THREAD

**Issue by nazar-pc** [scrutinizer-ci/scrutinizer#320]
I've changed config: tweaked some checks and excluded few directories, but instead of providing updated results I'm getting:
> Configuration has changed
> The configuration has changed since Scrutinizer has last run. This page might contain changes that are not related to code modifications.

> No notable changes
> There were no notable changes in the changeset which was inspected.

And, what is even more weird, on issues page:
> No Issues found
Congratulations, you have fixed all issues for the analyses that you have configured.

Also rating is `???` now.
https://scrutinizer-ci.com/g/nazar-pc/CleverStyle-CMS/issues

**Comment by schmittjoh** [comment]
Looking at your filter, you can remove the entire ``excluded_paths`` section as these paths are already excluded by your more specific ``paths`` section.

I'll close this here, please re-open if this still persists.

**Comment by nazar-pc** [comment]
Sorry, then I misunderstood config, I need to include everything excluding directories:
* components (while including components/modules/System)
* core/thirdparty
* tests

Looks like I've configured it wrong, can you give me some hints about this?
Documentation pages are linked to each other and no one of them gives good enough explanation for this case.

**Comment by schmittjoh** [comment]
Something like the following should work:

``
filter:
    excluded_paths:
        - core/thirdparty/
        - tests/

        # List all the excluded component sub-dirs explicitly
        - components/some-dir/
        - components/another-dir/      
``

**Comment by nazar-pc** [comment]
Ah, I see. Just thought it is possible to avoid somehow to list bunch of that directories.
Would be nice if:
* all directories included by default
* then excluded which I list to be excluded in config
* included directories that are included explicitly in config, even if some parent directory was excluded before

But looks like it should be separate issue with feature request, what you think?

**Comment by schmittjoh** [comment]
Yeah, maybe you can open a separate issue for that.
