### ISSUE TITLE
Auto-cancel duplicate inspections of the same PR

### ISSUE THREAD

**Issue by tonglil** [scrutinizer-ci/scrutinizer#329]
For a feature request down the road, it would be nice if there was a configuration setting to automatically cancel queued inspections of the same PR after a new commit has been pushed to that branch.

This reduces the redundant inspection as the code base has changed already and the status of the previous inspections are therefore irrelevant.

Thanks!

**Comment by schmittjoh** [comment]
Makes sense. I've created an issue for that.

**Comment by tonglil** [comment]
Thank you :)
