### ISSUE TITLE
Rating dropped radically in one commit that didn't touch mentioned code

### ISSUE THREAD

**Issue by nazar-pc** [scrutinizer-ci/scrutinizer#336]
https://scrutinizer-ci.com/g/nazar-pc/CleverStyle-CMS/inspections/7e131880-ca00-4dd1-8dfa-4e2dc135c493
All newly introduced things existed before and there is no update in blog about some engine changes, but my rating dropped by 1.1 in single commit.
WTF, scrutinizer?

**Comment by schmittjoh** [comment]
Traits are now also considered in the rating. This is what is affecting your score.

**Comment by nazar-pc** [comment]
It wasn't before?

**Comment by schmittjoh** [comment]
Yes, they we did not rate them before.

**Comment by nazar-pc** [comment]
Will there be any update in Blog about this major change?
