### ISSUE TITLE
New indentation option needed

### ISSUE THREAD

**Issue by nazar-pc** [scrutinizer-ci/scrutinizer#338]
I'm getting a lot of patch suggestions like this:
```diff
 /**
- * @package    CleverStyle CMS
- * @subpackage Builder
- * @author     Nazar Mokrynskyi <nazar@mokrynskyi.com>
- * @copyright  Copyright (c) 2011-2015, Nazar Mokrynskyi
- * @license    MIT License, see license.txt
- */
+		 * @package    CleverStyle CMS
+		 * @subpackage Builder
+		 * @author     Nazar Mokrynskyi <nazar@mokrynskyi.com>
+		 * @copyright  Copyright (c) 2011-2015, Nazar Mokrynskyi
+		 * @license    MIT License, see license.txt
+		 */
```
However, in files headers and PhpDoc blocks I do prefer to use 1 space, while 1 tab (4 spaces) in other places.

Is it possible to add additional configuration option for this?
I do not think anyone will ever like such code style (although I know some who prefer do not add any indentation here at all).

Example of project and report: https://scrutinizer-ci.com/g/nazar-pc/CleverStyle-CMS/inspections/cbc0da18-3434-4190-be3f-e6dca8c81856/patches?status=all

**Comment by nazar-pc** [comment]
Can anyone take a look at this, please?

**Comment by IlyaBakhlin** [comment]
I'd like to say I'm interested too in this topic, just because it's annoying to write a beautiful code and suffer the messages from the CI, suggesting to destroy that beauty.

People from Scrutinizer, please, check this issue.

**Comment by arosenhagen** [comment]
*bump* !

**Comment by Austinb** [comment]
Any word on fixing this or allow us to truly delete them?  Just bugs us ocd types who want to keep our patch list as clear as possible.  Basically every file in my project has a phpDoc header and every one of them also has an indentation patch fix for this header.  I have discarded those patches but every new file gets one and the old ones still remain.

**Comment by schmittjoh** [comment]
I've just checked the changelog of this component, and we had made a fix for this. Could you give a short example of the code/project which still has this bug?

**Comment by nazar-pc** [comment]
Looks like it is really fixed now, thanks!

**Comment by Austinb** [comment]
@schmittjoh It appears that they have gone away.  I ran an inspection today and that phpdoc in the head is not showing up. 

A new one that is puzzling me for php is when passing arguments by reference it wants a space between the "&" and the variable name. PSR-2 I believe is set for no space, that is what my editor does when set to psr-1/2 standard. 

Example:
```php
-    protected function processChannel($data, $fieldCount, Result &$result)
+    protected function processChannel($data, $fieldCount, Result & $result)
```

I can create a new issue.  Just interesting is started showing up.
