### ISSUE TITLE
Build always reported as "failed" (new repository, Travis-CI + ocular.phar)

### ISSUE THREAD

**Issue by Ocramius** [scrutinizer-ci/scrutinizer#341]
https://scrutinizer-ci.com/g/Roave/StrictPhp/inspections/e2ca9832-7b44-4a92-974a-ffb341b4f9ec reports that the build failed, but https://travis-ci.org/Roave/StrictPhp/jobs/68688411 actually succeeded and uploaded the ocular information correctly.

Am I missing something? Is ocular the notification vector, or is there another link between Scrutinizer-CI and Travis-CI in this build?

**Comment by schmittjoh** [comment]
It seems like there is a typo in the coverage file name "clover.xml" vs.
"coverage.clover". You also can see this in the output of the upload
command: "Notifying that no code coverage data is available for repository
"g/Roave/StrictPhp" and revision
"aa4261c9ff09e57d490203fe435ebe4273a6cb09"... Done"

**Comment by Ocramius** [comment]
ARGH! I'll fix and close the issue if it is that. Thanks!

**Comment by Ocramius** [comment]
Aaaaaaand that was it! Sorry for wasting your time :-\

**Comment by schmittjoh** [comment]
No problem, happy that I could help :)
