### ISSUE TITLE
Auto cancel on "random" inspections

### ISSUE THREAD

**Issue by senkal** [scrutinizer-ci/scrutinizer#344]
Hi,
currently I have an issue where scrutinizer auto cancels inspections with this message(and similar):

```
The expected parents 25286bf21381e6d24f34b3ea94e70341a997ee0a, bcf4868bdb629e7066c4dbe3ff6a2b40c92beec6 did not match the actual parents 25286bf21381e6d24f34b3ea94e70341a997ee0a, 825f58c18d9e8e96edb2b5011ab075e50b94bcaf of the merge commit. The remote refspec has changed since the inspection was scheduled.Parsing custom inspection configuration
```

First I thought there are some commits messages which can cancel inspection or PR's where we do some commits amends/rebase.
But no, even the most standard commits are cancelled.
Can send some urls to inspections where it happens.
It never happened before, started few days ago in random repositories/commits.
It happens for the last commits in PR so basically cancels whole PR inspection.
Is it our fault or something with scrutinizer/github?

![auto-cancel-scrutinizer](https://cloud.githubusercontent.com/assets/769204/8429445/93133df6-1f1f-11e5-81e8-ea10d90de7b7.png)
![auto-cancel-scrutinizer1](https://cloud.githubusercontent.com/assets/769204/8429447/96507736-1f1f-11e5-81cb-ee0539b489e9.png)

**Comment by schmittjoh** [comment]
This should only happen on pull-requests. Could you link to where you see this?

**Comment by senkal** [comment]
A yes sorry, wasn't clear enough.
It was Pull Request commit, so PR.
We fixed the issue by doing some extra commit on that branch/PR.
Here is where it failed:
https://scrutinizer-ci.com/g/feelunique/frontend/inspections/0cf40117-4886-440c-9146-e62e7c36754c

After some extra commits, just to trigger again Scrutinizer, it worked.
Any ideas what can we do wrong?

**Comment by schmittjoh** [comment]
This should only happen if we run on an older version of the pull-request. But as far as I understand, this happened on the most recent version of the pull-request for you?

**Comment by senkal** [comment]
Yes, it happened on the newest at the moment for 2-3 different PR's.
Can send you more examples if needed.

**Comment by senkal** [comment]
After some investigation we know we "break" our git sometimes.
So Scrutiizer was the first tool which found the issue.
We have later more issues.
In general what we did is possible but not good for us.
Scrutinizer is more stricted here what it's good.

Don't think it's really scrutinizer issue.
It just cancel inspections where you can messed up your git.

**Comment by senkal** [comment]
@schmittjoh unfortunately it happens for commits where, from git point of view(out workflow), all is fine. 
One PR commit passes, next one, with one simple change, is cancelled constantly.
I can't find the pattern here any more.

**Comment by schmittjoh** [comment]
Could you tell me a bit more about the other "breaking" change that you made before, maybe this is related and messed up our repository mirror.

**Comment by senkal** [comment]
Ok it looks like flow was like this:

* Push (1 commit)
  * commit [CI Green]
* Push (2 commits)
  *  Merge develop [CI skipped]
  * commit [CI Green]
* Push (1 commit)
  * commit [CI Cancelled]

Ok so probably the merge has something with it.

**Comment by schmittjoh** [comment]
I've had a look at this, and it seems related to a race-condition of when GitHub generates the "merged" version for pull-requests. 

We have deployed a fix now, so you should not get this message anymore. If you still do, please let me know.

**Comment by senkal** [comment]
@schmittjoh in the last 24 hours nothing happened.
I think it's safe to close this issue, looks like you fixed it.
Hopefully it won't happen again.
Thank you for help.
