### ISSUE TITLE
Code Rating was not enabled in your configuration. 

### ISSUE THREAD

**Issue by nazar-pc** [scrutinizer-ci/scrutinizer#349]
https://scrutinizer-ci.com/g/nazar-pc/CleverStyle-CMS/code-structure/master/hot-spots
Well, code rating was always available and I do not see any option to turn it on/off. What happened?

**Comment by Athari** [comment]
I've just rebuilt the project and information on the *Code / Hot Spots* tab appeared again. In my case, the last build was a long time ago, so maybe just some infrastructure changed in the service and old data couldn't be loaded.

**Comment by nazar-pc** [comment]
Yes, it appeared again after some time by itself.
It is so sad that last few months I do not get any response from developers here.

**Comment by kkamkou** [comment]
The same. I have to re-build it manually. + a lot of bugs with interface (fe: "Least tested Classes" click next, then back). Switched to CC.

**Comment by Athari** [comment]
@kkamkou The only problem is that Code Climate is a toy compared to Scrutinizer. :laughing:

**Comment by kkamkou** [comment]
Well, it is okay, as soon as CC shows me problems I have in the code.
