### ISSUE TITLE
Implement support for issue filters deactivation.

### ISSUE THREAD

**Issue by KelSolaar** [scrutinizer-ci/scrutinizer#355]
It seems to me that it is not possible to deactivate issue filters, that could be handy, especially if you have a lot and don't want to recreate them manually.

**Comment by schmittjoh** [comment]
You can remove an issue filter in your repository settings. We have some docs on this here:
https://scrutinizer-ci.com/docs/reviews/filtering_issues_and_false_positives#removing-created-filters-again

Let me know if this solves it.

**Comment by KelSolaar** [comment]
Hi,

It doesn't solve the issue as I was specifically specifying: `especially if you have a lot and don't want to recreate them manually.` I don't want to remove them, just a way to deactivate the filters.

**Comment by schmittjoh** [comment]
Could you elaborate some more what you would like to achieve? Would you like to see which issues are filtered?

**Comment by KelSolaar** [comment]
I have like [10 pages of filters](https://scrutinizer-ci.com/g/colour-science/colour/settings/issue-filters), some with scope specific to a module, some with whole repo scope, I'm not planning to redo them any time soon, but I would like to be able to toggle the filters on an off, this would be quite useful when scheduling inspections manually.

That being said, as I'm writing that, a better behaviour and workflow could be as follows: provide a link for each filter to a page enumerating everything they have actually filtered.

Cheers,

PS: Good job with *scrutinizer-ci* by the way, helped us increasing our code quality :)
