### ISSUE TITLE
Strange build failure conditions

### ISSUE THREAD

**Issue by yoanm** [scrutinizer-ci/scrutinizer#356]
Hi, 

I have a strange issue regarding build failure conditions.
I had a pull request with an inspection on the last commit that was OK and the build related to the pull request event was OK too. An inspection has been created when PR has been merged, and this one introduce a build failure that says i had an element with D rating. Is it normal that the two previous inspections were OK in that case ?
It's also strange because when I check on the code panel i only have elements with A or B rating, nothing with D rating!

Unfortunately, i cannot show you the code, as it's a private repository.

Do you have an explanation ?

Thanks.

**Comment by schmittjoh** [comment]
Hey,

we had a regression related to build failure conditions which might explain this. Could you maybe link to the inspection where you saw it so we can have a look?

**Comment by yoanm** [comment]
Hello,

Thanks for your quick reply, but, as i said, i cannot show you the codes nor the inspection while the repository is a company private one. 
We actually try to convert it to public one, we are just waiting for the approval.

I will get back to you when it's done.

Thanks for your help.

**Comment by yoanm** [comment]
Hello, 

We now have a public repository, but as we have made some changes on scrutinizer (dissociate the repository, delete it from scrutinizer, associate it again, etc), bug has disappear (as all olders inspections have been deleted too).

So, big thanks for your support :+1:

**Comment by schmittjoh** [comment]
Glad to hear it's solved!
