### ISSUE TITLE
Prefilled fields for creating new GitHub issues have less than useful info.

### ISSUE THREAD

**Issue by schlessera** [scrutinizer-ci/scrutinizer#369]
When creating a new GitHub issue from a Scrutinizer issue, the `Title` field is not prefilled at all, and the body only contains a single link that points back to Scrutinizer.

I would prefer to have this be more like what `Codacy` does. Let me show you an example.

Here's the issue in Scrutinizer:
![screenshot 2016-02-12 19 18 54](https://cloud.githubusercontent.com/assets/83631/13016212/a85d6e56-d1bd-11e5-9700-60439848b658.png)

This creates an issue where I have to manually set the title, and the content is only a link.

What I would really like to see is to have the prefilled title be the (truncated) message:
```
The call to ConfigInterface::getKey() has too many arguments starting with $keys.
```

The prefilled body could be something like this:

```
### [Scrutinizer](https://scrutinizer-ci.com/g/brightnucleus/config/inspections/5bdea880-b6e6-4d6b-b08c-0736a69f0483/issues/files/src/ConfigTrait.php?status=new&orderField=path&order=asc&honorSelectedPaths=0#inspectioncomment-10253434) detected an issue:
#### Message: `The call to ConfigInterface::getKey() has too many arguments starting with $keys.`

    
#### Occurred on:
+ **Commit**:  8638e99ea7b9ac19bcdf19c9ea1d6286ab06a7f7
+ **File**:    [src/ConfigTrait.php](https://github.com/brightnucleus/config/blob/8638e99ea7b9ac19bcdf19c9ea1d6286ab06a7f7/src/ConfigTrait.php)
+ **LineNum**: [45](https://github.com/brightnucleus/config/blob/8638e99ea7b9ac19bcdf19c9ea1d6286ab06a7f7/src/ConfigTrait.php#L45)
+ **Code**:    `    $config = new Config($config->getKey($keys));`

    
#### Currently on:
+ **Commit**:  8638e99ea7b9ac19bcdf19c9ea1d6286ab06a7f7
+ **File**:    [src/ConfigTrait.php](https://github.com/brightnucleus/config/blob/8638e99ea7b9ac19bcdf19c9ea1d6286ab06a7f7/src/ConfigTrait.php)
+ **LineNum**: [45](https://github.com/brightnucleus/config/blob/8638e99ea7b9ac19bcdf19c9ea1d6286ab06a7f7/src/ConfigTrait.php#L45)
```

Rendered result in ticket:
---
#### Occurred on:
+ **Commit**:  8638e99ea7b9ac19bcdf19c9ea1d6286ab06a7f7
+ **File**:    [src/ConfigTrait.php](https://github.com/brightnucleus/config/blob/8638e99ea7b9ac19bcdf19c9ea1d6286ab06a7f7/src/ConfigTrait.php)
+ **LineNum**: [45](https://github.com/brightnucleus/config/blob/8638e99ea7b9ac19bcdf19c9ea1d6286ab06a7f7/src/ConfigTrait.php#L45)
+ **Code**:    `    $config = new Config($config->getKey($keys));`

    
#### Currently on:
+ **Commit**:  8638e99ea7b9ac19bcdf19c9ea1d6286ab06a7f7
+ **File**:    [src/ConfigTrait.php](https://github.com/brightnucleus/config/blob/8638e99ea7b9ac19bcdf19c9ea1d6286ab06a7f7/src/ConfigTrait.php)
+ **LineNum**: [45](https://github.com/brightnucleus/config/blob/8638e99ea7b9ac19bcdf19c9ea1d6286ab06a7f7/src/ConfigTrait.php#L45)

**Comment by schmittjoh** [comment]
Thanks, I've moved this over to our internal tracker. It looks like a nice addition.
