### ISSUE TITLE
All issues are introduced in each inspections

### ISSUE THREAD

**Issue by yoanm** [scrutinizer-ci/scrutinizer#372]
Hello,

Some week ago, many inspections has failed because of issues that are fixed and same one are reintroduced. For example, a PR with less than 10 files and less than 50LOC, failed because **X issues are fixed** and **X+N issues are introduced**...

Now, we just have **X issues are introduced** with X = huge count of issues.

Example from yesterday : 
PR with 10 files and 430LOC (private repository, so i cannot show you) =>
<img width="577" alt="capture d ecran 2016-02-15 a 15 46 48" src="https://cloud.githubusercontent.com/assets/4410697/13071123/a5925566-d491-11e5-8908-a05c6d6858e1.png">

Just crazy, **2960 issues** introduced, and **12456 added class/operations**. For 10 files and 430LOC 0_o

Do you plan to do something ? Currently scrutinizer is become useless as it failed for dummy reasons.

**Comment by schmittjoh** [comment]
Do you have a link to your project, so we can have a look?

**Comment by yoanm** [comment]
I open a private conversation with intercom directly on the inspection page.
I cannot paste link here (company rules), sorry.

**Comment by schmittjoh** [comment]
No problem. Let's continue the conversation there. Closing this here.
