### ISSUE TITLE
Composer is not up to date

### ISSUE THREAD

**Issue by jmleroux** [scrutinizer-ci/scrutinizer#377]
We cannot run PHP Analyzer because of a Composer issue.

Failing analyzer : https://scrutinizer-ci.com/g/akeneo-labs/EnhancedConnectorBundle/inspections/9c84af48-15f4-4fb5-ba6b-049a5c3b78ab

And it seems the corresponding issue is this one : https://github.com/composer/composer/issues/5034

Regards,
JM

**Comment by schmittjoh** [comment]
Thanks for reporting. I've moved this to an internal issue. Closing this one here.

**Comment by jmleroux** [comment]
Just one question : how will we be noticed of the fix ?
