### ISSUE TITLE
Do not ignore PhpDoc on higher levels

### ISSUE THREAD

**Issue by nazar-pc** [scrutinizer-ci/scrutinizer#389]
One of the recurring problems I have is that Scrutinizer uses own type inferring information as the primary source of information.

What I'd like to see is that Scrutinizer checks PhpDoc correctness on method level, but beyond that method it actually uses information that was explicitly provided by developer in PhpDoc section regardless whether Scrutinizer think it is correct or not.

This would greatly reduce number of false-positive inspections.

**Comment by schmittjoh** [comment]
That's a really good suggestion, and our rewritten analysis will indeed work more like that.
