### ISSUE TITLE
Send external code coverage for JS project

### ISSUE THREAD

**Issue by alekitto** [scrutinizer-ci/scrutinizer#390]
I've read the documentation and i cannot found a tool for uploading code coverage to scrutinizer for a JS project, so i built it following the PHP ocular tool

Here's the repository: [alekitto/ocular.js](https://github.com/alekitto/ocular.js)

Since istanbul can generate coverage report in clover format, i can upload the report from travis CI with this configuration:

``` yml
after_success:
    - npm install ocular.js
    - $(npm bin)/ocular coverage/clover.xml
```

Hope this is appreciated! :)
Contributions are obviously welcome

**Comment by schmittjoh** [comment]
Great work on this! We'll have a look and add this to the documentation.

Thanks so much.

p.s. next time just send us a message via the support on the website, you'll get a much faster response there :)
