### ISSUE TITLE
PHP7+ support

### ISSUE THREAD

**Issue by theofidry** [scrutinizer-ci/scrutinizer#391]
Is there any plan to add a support for PHP7+ analysis? I believe the CI runs fine (I didn't check), but there is several doc warnings or PHP7+ specificities that scrutinizer doesn't seem to like.

**Comment by schmittjoh** [comment]
Could you maybe point to a project which shows the things that don't work? 

In general, PHP7 support was added last year, PHP7.1 might not be fully supported yet. For some things you need to require PHP7 in your composer.json for the analysis to work properly though.

**Comment by theofidry** [comment]
Sorry for the late answer. Cool to know you expect the support for it, as I have a projects in PHP7/7.1, I'll open an issue for each problem encountered on that side as I see them
