### ISSUE TITLE
PHPCS and other tools don't seem to run (correctly)

### ISSUE THREAD

**Issue by daften** [scrutinizer-ci/scrutinizer#392]
The file https://github.com/digipolisgent/robo-drupal-console/blob/feature/base/.scrutinizer.yml should drive ALL code checks. In a last act of desperation we even deleted the config on scrutinizer-ci.com itself. However, the checks don't seem correct.

We want to check against PSR-2. If we run phpcs locally as follows:
`phpcs --standard=PSR2 src/DrupalConsoleStack.php`
which gives 2 errors (and some warnings) as output:
```
101 | ERROR   | [x] TRUE, FALSE and NULL must be lowercase; expected
     |         |     "null" but found "NULL"
 703 | ERROR   | [x] The closing brace for the class must go on the
     |         |     next line after the body
```

However these errors are not shown in scrutinizer.

We don't understand why this is not even shown as a warning or a potential patch :s Nothing from the .scrutinizer.yml file in the tools seems to be taken into account. We've also searched the documentation, but can't find any specific references to these tools or their configuration, not even examples :s

**Comment by schmittjoh** [comment]
Could you open a support ticket on the website (there is a button in the bottom right). This helps us get back to you faster :)

I'm closing this here for the moment. Thanks so much.
