### ISSUE TITLE
Scrutinizer doesn't understand self

### ISSUE THREAD

**Issue by theofidry** [scrutinizer-ci/scrutinizer#393]
If you take the following piece of code:

```php
class Foo
{
  function withFoo(self $foo) {...}
}

$x = new Foo();
$x->withFoo($x);
```

You will get an error along the lines:

```
$x->withFoo($x) is of type object<Foo>, but the function expects a object<self>
```

**Comment by schmittjoh** [comment]
Thanks for the report. We do have an internal bug report open for this. I'm closing this one here for the moment.
