### ISSUE TITLE
Interface to see the list of ignored issues

### ISSUE THREAD

**Issue by stof** [scrutinizer-ci/scrutinizer#68]
It would be good to have a list of ignored issues (in a different page than the list of current issues) to be able to check what they were. The issue graph in the dashboard shows a second serie with the number of ignored issues but they cannot be accessed

**Comment by jcrben** [comment]
Sadly, I couldn't find this. Been a bit disappointed by how hard it is to navigate the Scrutinizer GUI.

Asked it in the Intercom as well. I'll try to put an answer in here since this is high on Google.
